[package]
name = "darkwallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
#miniquad = "0.4.0-alpha"
miniquad = { git = "https://github.com/not-fl3/miniquad" }
fontdue = "0.7"
image = "0.24"
log = "0.4.19"
glam = "0.27.0"
zmq = "0.10.0"
darkfi-serial = { path = "../../src/serial" }
thiserror = "1.0.57"
# Only for async Mutex
smol = "1.3.0"
atomic_float = "0.1.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"

[target.'cfg(target_os = "linux")'.dependencies]
simplelog = "0.12.1"

[package.metadata.android.activity_attributes]
"android:exported" = "true"
"android:windowSoftInputMode" = "adjustResize"

